### PR TITLE
Python test cases to meet expected outputs

### PR DESCRIPTION
**Pull request by haessar**

### CODE REVIEW

**Comment by haessar** [comment]
If you are happy with these changes, feel free to merge them into your fork, and then I can merge them into my master branch.

**Comment by lldelisle** [comment]
Great, I am going to try that.

**Comment by haessar** [comment]
Hang on just noticed a bug that I've introduced where transcripts start/end base aren't updating to match new UTR start/end base.

**Comment by lldelisle** [comment]
Thanks. For your information, I think it is ok not to output the transcript (at least for gtf), I personally tend to work with gtf without the 'transcript' just exon and CDS.

**Comment by lldelisle** [comment]
May I test with this version?

**Comment by lldelisle** [comment]
May I merge this but you don't merge my PR for the moment, there are other things I would like to work on.

**Comment by haessar** [comment]
Yes happy for you to do that.

**Pull request merged**
